apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer1-deployment
  labels:
    app: customer1
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer1
      environment: dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: customer1
        environment: dev
    spec:
      containers:
        - name: customer1-container
          image: divyajeetsingh/customer1:latest
          ports:
            - containerPort: 80
