apiVersion: v1
kind: Service
metadata:
  name: customer1-svc
  labels:
    app: customer1
    environment: dev
spec:
  type: NodePort
  selector:
    app: customer1
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32500
